version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.1.3
    - 6.1.4
  - dependency-name: com.gradle.plugin-publish
    versions:
    - 0.13.0
  - dependency-name: org.yaml:snakeyaml
    versions:
    - "1.27"
